import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "lo";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.ourProduct": "Our Product",
    "nav.performance": "Performance",
    "nav.pricing": "Pricing",
    "nav.about": "About",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.getStarted": "Get Started",
    
    // Hero Section
    "hero.tagline": "Professional EA Trading",
    "hero.title": "Trade Smarter with",
    "hero.titleHighlight": "AI-Powered EA",
    "hero.description": "Experience low-risk, sustainable trading with our professionally developed Expert Advisors. Designed for long-term capital preservation and consistent returns.",
    "hero.viewPerformance": "View Performance",
    "hero.explorePricing": "Explore Pricing",
    "hero.stat.maxDrawdown": "Max Drawdown",
    "hero.stat.winRate": "Win Rate",
    "hero.stat.yearsExperience": "Years Experience",
    
    // Features Section
    "features.tagline": "Why Choose Trade2live",
    "features.title": "Built for Serious Traders",
    "features.description": "Our Expert Advisors are designed with one goal: sustainable, long-term profitability with minimal risk.",
    "features.riskManagement": "Risk Management",
    "features.riskManagementDesc": "Advanced algorithms ensure your capital is protected with strict drawdown limits and position sizing.",
    "features.autoTrading": "24/7 Auto Trading",
    "features.autoTradingDesc": "Set it and forget it. Our EAs work around the clock, capturing opportunities in every market session.",
    "features.transparency": "Full Transparency",
    "features.transparencyDesc": "Real-time performance tracking with Myfxbook verification. No hidden results or cherry-picked data.",
    "features.support": "Expert Support",
    "features.supportDesc": "Dedicated support team to help you with setup, optimization, and any questions you may have.",
    
    // EA Overview Section
    "eaOverview.tagline": "Our Expert Advisors",
    "eaOverview.title": "Choose Your Trading System",
    "eaOverview.description": "Two distinct strategies designed for different market conditions and trading preferences.",
    "eaOverview.icf.name": "Trade2live ICF$",
    "eaOverview.icf.description": "Optimized for volatile market conditions with quick profit-taking and tight stop losses.",
    "eaOverview.icf.strategy": "Scalping & Intraday",
    "eaOverview.icf.pairs": "Major Pairs",
    "eaOverview.icf.maxDrawdown": "Max DD: 15%",
    "eaOverview.zb.name": "Trade2live ZB$",
    "eaOverview.zb.description": "Designed for stable, consistent returns with longer holding periods and trend following.",
    "eaOverview.zb.strategy": "Swing Trading",
    "eaOverview.zb.pairs": "Multi-Currency",
    "eaOverview.zb.maxDrawdown": "Max DD: 12%",
    "eaOverview.learnMore": "Learn More",
    
    // Testimonials Section
    "testimonials.tagline": "Testimonials",
    "testimonials.title": "What Our Clients Say",
    "testimonials.description": "Real feedback from traders who trust Trade2live for their automated trading needs.",
    
    // CTA Section
    "cta.title": "Ready to Start Trading?",
    "cta.description": "Join thousands of traders who trust Trade2live for consistent, low-risk automated trading.",
    "cta.viewPricing": "View Pricing",
    "cta.contactUs": "Contact Us",
    
    // Footer
    "footer.description": "Professional EA trading solutions for sustainable, long-term growth.",
    "footer.products": "Products",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.terms": "Terms & Conditions",
    "footer.privacy": "Privacy Policy",
    "footer.refund": "Refund Policy",
    "footer.copyright": "© 2024 Trade2live. All rights reserved.",
    "footer.riskWarning": "Risk Warning: Trading forex carries a high level of risk and may not be suitable for all investors.",
    
    // About Page
    "about.title": "About Trade2live",
    "about.subtitle": "Professional EA Trading Solutions",
    "about.tagline": "About Us",
    "about.heroTitle": "Building the Future of",
    "about.heroHighlight": "Automated Trading",
    "about.heroDescription": "Trade2live is a premium Expert Advisor service dedicated to providing sustainable, low-risk automated trading solutions for serious investors.",
    "about.storyTitle": "Our Story",
    "about.storyP1": "Trade2live was founded by a team of experienced forex traders and software developers who were frustrated with the unreliable and overhyped EA market.",
    "about.storyP2": "After years of developing and testing various strategies, we created a set of Expert Advisors that prioritize what matters most:",
    "about.storyP2Highlight1": "capital preservation",
    "about.storyP2Highlight2": "sustainable growth",
    "about.storyP3": "Our philosophy is simple — trading is a long-term game. We don't promise overnight riches, but we do deliver consistent, verified results that speak for themselves.",
    "about.journeyTitle": "Our Journey",
    "about.valuesTagline": "Our Values",
    "about.valuesTitle": "What We",
    "about.valuesHighlight": "Stand For",
    "about.valueRiskFirst": "Risk First",
    "about.valueRiskFirstDesc": "We prioritize capital preservation over aggressive returns. Every strategy is built with risk management at its core.",
    "about.valueSustainable": "Sustainable Growth",
    "about.valueSustainableDesc": "Our systems are designed for long-term profitability, not quick wins. Consistency is our priority.",
    "about.valueTransparency": "Transparency",
    "about.valueTransparencyDesc": "All our results are publicly verified. We believe in complete transparency with our trading community.",
    "about.valueCommunity": "Community",
    "about.valueCommunityDesc": "We're building a community of serious traders who understand that successful trading is a marathon, not a sprint.",
    "about.statActiveUsers": "Active Users",
    "about.statYearsExp": "Years Experience",
    "about.statVolume": "Volume Traded",
    "about.statSupport": "Support Available",
    "about.ctaTitle": "Join Our Trading Community",
    "about.ctaDescription": "Experience the difference of professional-grade automated trading with verified results and dedicated support.",
    "about.viewPlans": "View Plans",
    "about.timeline2019": "Started developing proprietary trading algorithms",
    "about.timeline2020": "Launched Trade2live ICF$ for private testing",
    "about.timeline2021": "Released ZB$ strategy, expanded to beta users",
    "about.timeline2022": "Public launch with verified Myfxbook tracking",
    "about.timeline2023": "Reached 500+ active users across Thailand",
    "about.timeline2024": "Continuous improvement and new features",
    
    // Pricing Page
    "pricing.title": "Simple, Transparent Pricing",
    "pricing.subtitle": "Choose the plan that fits your trading needs",
    "pricing.tagline": "Pricing",
    "pricing.heroTitle": "Choose Your",
    "pricing.heroHighlight": "Plan",
    "pricing.heroDescription": "Flexible subscription options for every trading style. All plans include full EA access, updates, and support.",
    "pricing.3months": "3 Months",
    "pricing.6months": "6 Months",
    "pricing.12months": "12 Months",
    "pricing.mostPopular": "Most Popular",
    "pricing.bestValue": "Best Value",
    "pricing.recommended": "⭐ Recommended",
    "pricing.subscribe": "Subscribe",
    "pricing.getBundle": "Get Bundle",
    "pricing.icfTitle": "Trade2live ICF$",
    "pricing.icfSubtitle": "Intelligent Capital Flow Strategy",
    "pricing.zbTitle": "Trade2live ZB$",
    "pricing.zbSubtitle": "Zero-Based Risk Strategy",
    "pricing.bundleTitle": "Premium Bundle",
    "pricing.bundleSubtitle": "Both EA Systems • Best Value",
    "pricing.individualIncludes": "Individual EA Plan Includes",
    "pricing.bundleIncludes": "Premium Bundle Includes",
    "pricing.feature1": "Licensed for 1 MT4/MT5 Account",
    "pricing.feature2": "Free EA Updates",
    "pricing.feature3": "Setup Guide & Documentation",
    "pricing.feature4": "Technical Support via Line/Telegram",
    "pricing.feature5": "Access to Private Community",
    "pricing.bundleFeature1": "Both ICF$ and ZB$ EA",
    "pricing.bundleFeature2": "Licensed for 2 MT4/MT5 Accounts",
    "pricing.bundleFeature3": "Priority Support",
    "pricing.bundleFeature4": "Free EA Updates",
    "pricing.bundleFeature5": "VIP Community Access",
    "pricing.bundleFeature6": "Monthly Strategy Calls",
    "pricing.ctaTitle": "Have Questions About Pricing?",
    "pricing.ctaDescription": "Contact our team for custom solutions or any inquiries.",
    
    // Contact Page
    "contact.title": "Get in Touch",
    "contact.subtitle": "We're here to help you succeed",
    "contact.tagline": "Contact Us",
    "contact.heroTitle": "Get in",
    "contact.heroHighlight": "Touch",
    "contact.heroDescription": "Have questions about our EA systems? Our team is here to help.",
    "contact.lineFastest": "Fastest response time",
    "contact.telegram247": "24/7 support channel",
    "contact.emailDetailed": "For detailed inquiries",
    "contact.facebookCommunity": "Community updates",
    "contact.sendMessage": "Send us a Message",
    "contact.name": "Name",
    "contact.namePlaceholder": "Your name",
    "contact.email": "Email",
    "contact.emailPlaceholder": "your@email.com",
    "contact.subject": "Subject",
    "contact.subjectPlaceholder": "How can we help?",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us more about your inquiry...",
    "contact.send": "Send Message",
    "contact.supportInfo": "Support Information",
    "contact.workingHours": "Working Hours",
    "contact.weekday": "Monday - Friday: 9:00 - 21:00 (GMT+7)",
    "contact.weekend": "Weekend: 10:00 - 18:00 (GMT+7)",
    "contact.responseTime": "Response Time",
    "contact.lineTelegram": "Line / Telegram",
    "contact.technicalIssues": "Technical Issues",
    "contact.priority": "Priority",
    "contact.premiumSupport": "Premium Support",
    "contact.premiumDescription": "Bundle subscribers receive priority support with dedicated assistance and monthly strategy consultation calls.",
    "contact.messageSent": "Message Sent!",
    "contact.messageSuccess": "We'll get back to you within 24 hours.",
    
    // FAQ Page
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Find answers to common questions",
    "faq.tagline": "FAQ",
    "faq.heroTitle": "Frequently Asked",
    "faq.heroHighlight": "Questions",
    "faq.heroDescription": "Find answers to common questions about our EA trading systems.",
    "faq.generalQuestions": "General Questions",
    "faq.capitalInvestment": "Capital & Investment",
    "faq.technicalRequirements": "Technical Requirements",
    "faq.subscriptionSupport": "Subscription & Support",
    "faq.stillHaveQuestions": "Still Have Questions?",
    "faq.cantFind": "Can't find what you're looking for? Our support team is here to help.",
    "faq.contactSupport": "Contact Support",
    
    // Performance Page
    "performance.title": "Live Performance",
    "performance.subtitle": "Real-time verified trading results",
    "performance.tagline": "Live Performance",
    "performance.heroTitle": "Verified",
    "performance.heroHighlight": "Results",
    "performance.heroDescription": "Real-time performance data from our live trading accounts. All results are tracked and verified through Myfxbook.",
    "performance.totalReturn": "Total Return",
    "performance.live": "Live",
    "performance.monthlyAvg": "Monthly Avg",
    "performance.maxDD": "Max DD",
    "performance.winRate": "Win Rate",
    "performance.profitFactor": "Profit Factor",
    "performance.equityCurve": "Equity Curve (12 Months)",
    "performance.startingBalance": "Starting balance: $10,000",
    "performance.monthlyReturns": "Monthly Returns (%)",
    "performance.detailedStats": "Detailed Statistics",
    "performance.totalTrades": "Total Trades",
    "performance.tradingDays": "Trading Days",
    "performance.sharpeRatio": "Sharpe Ratio",
    "performance.monthlyAverage": "Monthly Average",
    "performance.maxDrawdown": "Max Drawdown",
    "performance.myfxbookTitle": "Live Myfxbook Verification",
    "performance.myfxbookDescription": "View our fully verified live trading results on Myfxbook",
    "performance.viewMyfxbook": "View on Myfxbook",
    "performance.ctaTitle": "Start Trading with",
    "performance.ctaHighlight": "Proven Results",
    "performance.ctaDescription": "Join our growing community of successful automated traders.",
    
    // Copy Trade Page
    "copyTrade.tagline": "Copy Trade Service",
    "copyTrade.heroTitle": "Copy Professional Traders",
    "copyTrade.heroHighlight": "Automatically",
    "copyTrade.heroDescription": "Don't have time to trade? Let our expert traders do it for you. Copy their trades automatically and grow your account with minimal effort.",
    "copyTrade.startCopyTrading": "Start Copy Trading",
    "copyTrade.askQuestions": "Ask Questions",
    "copyTrade.activeCopiers": "Active Copiers",
    "copyTrade.copiedVolume": "Copied Volume",
    "copyTrade.autoTrading": "Auto Trading",
    "copyTrade.whyChooseTitle": "Why Choose",
    "copyTrade.whyChooseHighlight": "Copy Trade",
    "copyTrade.whyChooseDescription": "Experience the benefits of professional trading without the learning curve.",
    "copyTrade.easyCopyTrading": "Easy Copy Trading",
    "copyTrade.easyCopyTradingDesc": "Copy trades from professional traders automatically. No trading experience required.",
    "copyTrade.provenPerformance": "Proven Performance",
    "copyTrade.provenPerformanceDesc": "Follow traders with verified track records and consistent profitability.",
    "copyTrade.riskManagement": "Risk Management",
    "copyTrade.riskManagementDesc": "Set your own risk limits and stop-loss parameters for complete control.",
    "copyTrade.realTimeExecution": "Real-time Execution",
    "copyTrade.realTimeExecutionDesc": "Trades are copied instantly to your account with minimal latency.",
    "copyTrade.howItWorksTitle": "How It",
    "copyTrade.howItWorksHighlight": "Works",
    "copyTrade.howItWorksDescription": "Get started in four simple steps and begin copying trades today.",
    "copyTrade.step1Title": "Choose a Signal Provider",
    "copyTrade.step1Desc": "Browse our verified traders and select one that matches your risk tolerance and trading style.",
    "copyTrade.step2Title": "Connect Your Account",
    "copyTrade.step2Desc": "Link your MT4/MT5 trading account securely. Your funds stay with your broker.",
    "copyTrade.step3Title": "Set Your Parameters",
    "copyTrade.step3Desc": "Configure your lot size, risk limits, and which pairs to copy. Full control is yours.",
    "copyTrade.step4Title": "Start Copying",
    "copyTrade.step4Desc": "Trades are automatically copied to your account in real-time. Sit back and watch.",
    "copyTrade.benefitsTitle": "Everything You Need to",
    "copyTrade.benefitsHighlight": "Succeed",
    "copyTrade.benefitsDescription": "Our copy trading service is designed to make automated trading accessible to everyone, regardless of experience level.",
    "copyTrade.benefit1": "No trading experience needed",
    "copyTrade.benefit2": "Automatic position sizing",
    "copyTrade.benefit3": "Real-time trade copying",
    "copyTrade.benefit4": "Choose from multiple signal providers",
    "copyTrade.benefit5": "Set your own risk limits",
    "copyTrade.benefit6": "Transparent performance history",
    "copyTrade.benefit7": "Easy setup in minutes",
    "copyTrade.benefit8": "Works with any MT4/MT5 broker",
    "copyTrade.proSignalProvider": "Pro Signal Provider",
    "copyTrade.topPerforming": "Top Performing Trader",
    "copyTrade.monthlyReturn": "Monthly Return",
    "copyTrade.tradingSince": "Trading Since",
    "copyTrade.copyThisTrader": "Copy This Trader",
    "copyTrade.simplePricing": "Simple",
    "copyTrade.pricingHighlight": "Pricing",
    "copyTrade.pricingDescription": "Choose a plan that fits your trading needs. No hidden fees.",
    "copyTrade.fullAccess": "Full access to copy trading service",
    "copyTrade.pricingFeature1": "Unlimited trade copying",
    "copyTrade.pricingFeature2": "Multiple signal providers",
    "copyTrade.pricingFeature3": "Real-time execution",
    "copyTrade.pricingFeature4": "Risk management tools",
    "copyTrade.pricingFeature5": "24/7 support",
    "copyTrade.pricingFeature6": "Performance analytics",
    "copyTrade.ctaTitle": "Ready to Start",
    "copyTrade.ctaHighlight": "Copy Trading",
    "copyTrade.ctaDescription": "Join hundreds of traders who are already copying our expert signals and growing their accounts automatically.",
    "copyTrade.viewAllPlans": "View All Plans",
  },
  lo: {
    // Navbar
    "nav.home": "ໜ້າຫຼັກ",
    "nav.ourProduct": "ຜະລິດຕະພັນ",
    "nav.performance": "ຜົນງານ",
    "nav.pricing": "ລາຄາ",
    "nav.about": "ກ່ຽວກັບ",
    "nav.faq": "ຄຳຖາມທີ່ພົບເລື້ອຍ",
    "nav.contact": "ຕິດຕໍ່",
    "nav.getStarted": "ເລີ່ມຕົ້ນ",
    
    // Hero Section
    "hero.tagline": "ການຊື້ຂາຍ EA ແບບມືອາຊີບ",
    "hero.title": "ຊື້ຂາຍອັດສະລິຍະກັບ",
    "hero.titleHighlight": "EA ທີ່ຂັບເຄື່ອນດ້ວຍ AI",
    "hero.description": "ປະສົບການການຊື້ຂາຍທີ່ມີຄວາມສ່ຽງຕ່ຳ ແລະ ຍືນຍົງດ້ວຍທີ່ປຶກສາຜູ້ຊ່ຽວຊານທີ່ພັດທະນາຂຶ້ນຢ່າງມືອາຊີບ. ອອກແບບມາເພື່ອການອະນຸລັກທຶນໃນໄລຍະຍາວ ແລະ ຜົນຕອບແທນທີ່ສະໝ່ຳສະເໝີ.",
    "hero.viewPerformance": "ເບິ່ງຜົນງານ",
    "hero.explorePricing": "ເບິ່ງລາຄາ",
    "hero.stat.maxDrawdown": "ການຫຼຸດສູງສຸດ",
    "hero.stat.winRate": "ອັດຕາຊະນະ",
    "hero.stat.yearsExperience": "ປີປະສົບການ",
    
    // Features Section
    "features.tagline": "ເປັນຫຍັງຕ້ອງເລືອກ Trade2live",
    "features.title": "ສ້າງຂຶ້ນສຳລັບນັກເທຣດມືອາຊີບ",
    "features.description": "ທີ່ປຶກສາຜູ້ຊ່ຽວຊານຂອງພວກເຮົາຖືກອອກແບບມາດ້ວຍເປົ້າໝາຍດຽວ: ຄວາມສາມາດໃນການທຳກຳໄລທີ່ຍືນຍົງໃນໄລຍະຍາວດ້ວຍຄວາມສ່ຽງໜ້ອຍທີ່ສຸດ.",
    "features.riskManagement": "ການຄຸ້ມຄອງຄວາມສ່ຽງ",
    "features.riskManagementDesc": "ລະບົບອັດຕະໂນມັດຂັ້ນສູງຮັບປະກັນວ່າທຶນຂອງທ່ານໄດ້ຮັບການປົກປ້ອງດ້ວຍຂໍ້ຈຳກັດການຫຼຸດ ແລະ ຂະໜາດຕຳແໜ່ງທີ່ເຂັ້ມງວດ.",
    "features.autoTrading": "ການຊື້ຂາຍອັດຕະໂນມັດ 24/7",
    "features.autoTradingDesc": "ຕັ້ງຄ່າແລ້ວລືມມັນໄປ. EA ຂອງພວກເຮົາເຮັດວຽກຕະຫຼອດເວລາ, ຈັບໂອກາດໃນທຸກໆຊ່ວງຕະຫຼາດ.",
    "features.transparency": "ຄວາມໂປ່ງໃສຢ່າງເຕັມທີ່",
    "features.transparencyDesc": "ການຕິດຕາມຜົນງານແບບເວລາຈິງດ້ວຍການຢັ້ງຢືນຈາກ Myfxbook. ບໍ່ມີຜົນລັບທີ່ເຊື່ອງໄວ້ຫຼືຂໍ້ມູນທີ່ຄັດເລືອກ.",
    "features.support": "ການສະໜັບສະໜູນຈາກຜູ້ຊ່ຽວຊານ",
    "features.supportDesc": "ທີມງານສະໜັບສະໜູນທີ່ອຸທິດຕົນເພື່ອຊ່ວຍທ່ານໃນການຕັ້ງຄ່າ, ການເພີ່ມປະສິດທິພາບ, ແລະຄຳຖາມທີ່ທ່ານອາດຈະມີ.",
    
    // EA Overview Section
    "eaOverview.tagline": "ທີ່ປຶກສາຜູ້ຊ່ຽວຊານຂອງພວກເຮົາ",
    "eaOverview.title": "ເລືອກລະບົບການຊື້ຂາຍຂອງທ່ານ",
    "eaOverview.description": "ສອງກົນລະຍຸດທີ່ແຕກຕ່າງກັນອອກແບບມາສຳລັບສະພາບຕະຫຼາດ ແລະ ຄວາມມັກໃນການຊື້ຂາຍທີ່ແຕກຕ່າງກັນ.",
    "eaOverview.icf.name": "Trade2live ICF$",
    "eaOverview.icf.description": "ປັບປຸງໃຫ້ເໝາະສົມສຳລັບສະພາບຕະຫຼາດທີ່ຜັນຜວນດ້ວຍການທຳກຳໄລໄວ ແລະ ການຢຸດການຂາດທຶນທີ່ເຂັ້ມງວດ.",
    "eaOverview.icf.strategy": "Scalping & Intraday",
    "eaOverview.icf.pairs": "ຄູ່ຫຼັກ",
    "eaOverview.icf.maxDrawdown": "DD ສູງສຸດ: 15%",
    "eaOverview.zb.name": "Trade2live ZB$",
    "eaOverview.zb.description": "ອອກແບບມາສຳລັບຜົນຕອບແທນທີ່ໝັ້ນຄົງ ແລະ ສະໝ່ຳສະເໝີດ້ວຍໄລຍະເວລາການຖືຄອງທີ່ຍາວນານ ແລະ ການຕິດຕາມແນວໂນ້ມ.",
    "eaOverview.zb.strategy": "Swing Trading",
    "eaOverview.zb.pairs": "ຫຼາຍສະກຸນເງິນ",
    "eaOverview.zb.maxDrawdown": "DD ສູງສຸດ: 12%",
    "eaOverview.learnMore": "ຮຽນຮູ້ເພີ່ມເຕີມ",
    
    // Testimonials Section
    "testimonials.tagline": "ຄຳຊົມເຊີຍ",
    "testimonials.title": "ລູກຄ້າຂອງພວກເຮົາເວົ້າຫຍັງ",
    "testimonials.description": "ຄຳຕິຊົມຈິງຈາກນັກເທຣດທີ່ໄວ້ວາງໃຈ Trade2live ສຳລັບຄວາມຕ້ອງການການຊື້ຂາຍອັດຕະໂນມັດຂອງພວກເຂົາ.",
    
    // CTA Section
    "cta.title": "ພ້ອມທີ່ຈະເລີ່ມຊື້ຂາຍບໍ?",
    "cta.description": "ເຂົ້າຮ່ວມກັບນັກເທຣດຫຼາຍພັນຄົນທີ່ໄວ້ວາງໃຈ Trade2live ສຳລັບການຊື້ຂາຍອັດຕະໂນມັດທີ່ມີຄວາມສ່ຽງຕ່ຳ ແລະ ສະໝ່ຳສະເໝີ.",
    "cta.viewPricing": "ເບິ່ງລາຄາ",
    "cta.contactUs": "ຕິດຕໍ່ພວກເຮົາ",
    
    // Footer
    "footer.description": "ວິທີແກ້ໄຂການຊື້ຂາຍ EA ແບບມືອາຊີບສຳລັບການເຕີບໂຕທີ່ຍືນຍົງໃນໄລຍະຍາວ.",
    "footer.products": "ຜະລິດຕະພັນ",
    "footer.company": "ບໍລິສັດ",
    "footer.legal": "ກົດໝາຍ",
    "footer.terms": "ເງື່ອນໄຂ ແລະ ຂໍ້ກຳນົດ",
    "footer.privacy": "ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ",
    "footer.refund": "ນະໂຍບາຍການຄືນເງິນ",
    "footer.copyright": "© 2024 Trade2live. ສະຫງວນລິຂະສິດ.",
    "footer.riskWarning": "ຄຳເຕືອນຄວາມສ່ຽງ: ການຊື້ຂາຍ forex ມີຄວາມສ່ຽງສູງ ແລະ ອາດບໍ່ເໝາະສົມສຳລັບນັກລົງທຶນທຸກຄົນ.",
    
    // About Page
    "about.title": "ກ່ຽວກັບ Trade2live",
    "about.subtitle": "ວິທີແກ້ໄຂການຊື້ຂາຍ EA ແບບມືອາຊີບ",
    "about.tagline": "ກ່ຽວກັບພວກເຮົາ",
    "about.heroTitle": "ສ້າງອະນາຄົດຂອງ",
    "about.heroHighlight": "ການຊື້ຂາຍອັດຕະໂນມັດ",
    "about.heroDescription": "Trade2live ເປັນບໍລິການ Expert Advisor ລະດັບພຣີມຽມທີ່ອຸທິດຕົນເພື່ອສະໜອງວິທີແກ້ໄຂການຊື້ຂາຍອັດຕະໂນມັດທີ່ຍືນຍົງ ແລະ ມີຄວາມສ່ຽງຕ່ຳສຳລັບນັກລົງທຶນທີ່ຈິງຈັງ.",
    "about.storyTitle": "ເລື່ອງລາວຂອງພວກເຮົາ",
    "about.storyP1": "Trade2live ຖືກກໍ່ຕັ້ງຂຶ້ນໂດຍທີມງານນັກເທຣດ forex ທີ່ມີປະສົບການ ແລະ ນັກພັດທະນາຊອບແວທີ່ຜິດຫວັງກັບຕະຫຼາດ EA ທີ່ບໍ່ໜ້າເຊື່ອຖື ແລະ ໂຄສະນາເກີນຈິງ.",
    "about.storyP2": "ຫຼັງຈາກຫຼາຍປີຂອງການພັດທະນາ ແລະ ທົດສອບກົນລະຍຸດຕ່າງໆ, ພວກເຮົາໄດ້ສ້າງຊຸດ Expert Advisors ທີ່ໃຫ້ຄວາມສຳຄັນກັບສິ່ງທີ່ສຳຄັນທີ່ສຸດ:",
    "about.storyP2Highlight1": "ການອະນຸລັກທຶນ",
    "about.storyP2Highlight2": "ການເຕີບໂຕທີ່ຍືນຍົງ",
    "about.storyP3": "ປັດຊະຍາຂອງພວກເຮົາແມ່ນງ່າຍດາຍ — ການຊື້ຂາຍແມ່ນເກມໄລຍະຍາວ. ພວກເຮົາບໍ່ສັນຍາຄວາມຮັ່ງມີຂ້າມຄືນ, ແຕ່ພວກເຮົາສົ່ງຜົນລັບທີ່ສະໝ່ຳສະເໝີ ແລະ ຢັ້ງຢືນໄດ້ທີ່ເວົ້າແທນຕົວເອງ.",
    "about.journeyTitle": "ການເດີນທາງຂອງພວກເຮົາ",
    "about.valuesTagline": "ຄຸນຄ່າຂອງພວກເຮົາ",
    "about.valuesTitle": "ສິ່ງທີ່ພວກເຮົາ",
    "about.valuesHighlight": "ຍຶດໝັ້ນ",
    "about.valueRiskFirst": "ຄວາມສ່ຽງມາກ່ອນ",
    "about.valueRiskFirstDesc": "ພວກເຮົາໃຫ້ຄວາມສຳຄັນກັບການອະນຸລັກທຶນຫຼາຍກວ່າຜົນຕອບແທນທີ່ຮຸນແຮງ. ທຸກກົນລະຍຸດຖືກສ້າງຂຶ້ນດ້ວຍການຄຸ້ມຄອງຄວາມສ່ຽງເປັນຫຼັກ.",
    "about.valueSustainable": "ການເຕີບໂຕທີ່ຍືນຍົງ",
    "about.valueSustainableDesc": "ລະບົບຂອງພວກເຮົາຖືກອອກແບບມາສຳລັບຄວາມສາມາດທຳກຳໄລໃນໄລຍະຍາວ, ບໍ່ແມ່ນໄຊຊະນະໄວ. ຄວາມສະໝ່ຳສະເໝີແມ່ນບູລິມະສິດຂອງພວກເຮົາ.",
    "about.valueTransparency": "ຄວາມໂປ່ງໃສ",
    "about.valueTransparencyDesc": "ຜົນລັບທັງໝົດຂອງພວກເຮົາຖືກຢັ້ງຢືນຕໍ່ສາທາລະນະ. ພວກເຮົາເຊື່ອໃນຄວາມໂປ່ງໃສຢ່າງເຕັມທີ່ກັບຊຸມຊົນການຊື້ຂາຍຂອງພວກເຮົາ.",
    "about.valueCommunity": "ຊຸມຊົນ",
    "about.valueCommunityDesc": "ພວກເຮົາກຳລັງສ້າງຊຸມຊົນນັກເທຣດທີ່ຈິງຈັງທີ່ເຂົ້າໃຈວ່າການຊື້ຂາຍທີ່ປະສົບຜົນສຳເລັດແມ່ນການແລ່ນມາຣາທອນ, ບໍ່ແມ່ນການແລ່ນສັ້ນ.",
    "about.statActiveUsers": "ຜູ້ໃຊ້ງານ",
    "about.statYearsExp": "ປີປະສົບການ",
    "about.statVolume": "ປະລິມານການຊື້ຂາຍ",
    "about.statSupport": "ການສະໜັບສະໜູນ",
    "about.ctaTitle": "ເຂົ້າຮ່ວມຊຸມຊົນການຊື້ຂາຍຂອງພວກເຮົາ",
    "about.ctaDescription": "ສຳຜັດຄວາມແຕກຕ່າງຂອງການຊື້ຂາຍອັດຕະໂນມັດລະດັບມືອາຊີບດ້ວຍຜົນລັບທີ່ຢັ້ງຢືນ ແລະ ການສະໜັບສະໜູນທີ່ອຸທິດຕົນ.",
    "about.viewPlans": "ເບິ່ງແພັກເກດ",
    "about.timeline2019": "ເລີ່ມພັດທະນາ algorithms ການຊື້ຂາຍເປັນເອກະສິດ",
    "about.timeline2020": "ເປີດຕົວ Trade2live ICF$ ສຳລັບການທົດສອບສ່ວນຕົວ",
    "about.timeline2021": "ເປີດຕົວກົນລະຍຸດ ZB$, ຂະຫຍາຍໄປຫາຜູ້ໃຊ້ເບຕ້າ",
    "about.timeline2022": "ເປີດຕົວສາທາລະນະດ້ວຍການຕິດຕາມ Myfxbook ທີ່ຢັ້ງຢືນ",
    "about.timeline2023": "ມີຜູ້ໃຊ້ 500+ ຄົນໃນທົ່ວປະເທດໄທ",
    "about.timeline2024": "ການປັບປຸງຢ່າງຕໍ່ເນື່ອງ ແລະ ຄຸນສົມບັດໃໝ່",
    
    // Pricing Page
    "pricing.title": "ລາຄາງ່າຍໆ ໂປ່ງໃສ",
    "pricing.subtitle": "ເລືອກແພັກເກດທີ່ເໝາະກັບຄວາມຕ້ອງການການຊື້ຂາຍຂອງທ່ານ",
    "pricing.tagline": "ລາຄາ",
    "pricing.heroTitle": "ເລືອກ",
    "pricing.heroHighlight": "ແພັກເກດ",
    "pricing.heroDescription": "ຕົວເລືອກການສະໝັກສະມາຊິກທີ່ຍືດຫຍຸ່ນສຳລັບທຸກຮູບແບບການຊື້ຂາຍ. ແພັກເກດທັງໝົດລວມມີການເຂົ້າເຖິງ EA ເຕັມຮູບແບບ, ອັບເດດ, ແລະ ການສະໜັບສະໜູນ.",
    "pricing.3months": "3 ເດືອນ",
    "pricing.6months": "6 ເດືອນ",
    "pricing.12months": "12 ເດືອນ",
    "pricing.mostPopular": "ນິຍົມທີ່ສຸດ",
    "pricing.bestValue": "ຄຸ້ມຄ່າທີ່ສຸດ",
    "pricing.recommended": "⭐ ແນະນຳ",
    "pricing.subscribe": "ສະໝັກ",
    "pricing.getBundle": "ຮັບ Bundle",
    "pricing.icfTitle": "Trade2live ICF$",
    "pricing.icfSubtitle": "ກົນລະຍຸດ Intelligent Capital Flow",
    "pricing.zbTitle": "Trade2live ZB$",
    "pricing.zbSubtitle": "ກົນລະຍຸດ Zero-Based Risk",
    "pricing.bundleTitle": "Premium Bundle",
    "pricing.bundleSubtitle": "ລະບົບ EA ທັງສອງ • ຄຸ້ມຄ່າທີ່ສຸດ",
    "pricing.individualIncludes": "ແພັກເກດ EA ແຕ່ລະອັນລວມມີ",
    "pricing.bundleIncludes": "Premium Bundle ລວມມີ",
    "pricing.feature1": "ລາຍເຊັນສຳລັບ 1 ບັນຊີ MT4/MT5",
    "pricing.feature2": "ອັບເດດ EA ຟຣີ",
    "pricing.feature3": "ຄູ່ມືການຕັ້ງຄ່າ & ເອກະສານ",
    "pricing.feature4": "ການສະໜັບສະໜູນດ້ານເທັກນິກຜ່ານ Line/Telegram",
    "pricing.feature5": "ການເຂົ້າເຖິງຊຸມຊົນສ່ວນຕົວ",
    "pricing.bundleFeature1": "EA ທັງ ICF$ ແລະ ZB$",
    "pricing.bundleFeature2": "ລາຍເຊັນສຳລັບ 2 ບັນຊີ MT4/MT5",
    "pricing.bundleFeature3": "ການສະໜັບສະໜູນບູລິມະສິດ",
    "pricing.bundleFeature4": "ອັບເດດ EA ຟຣີ",
    "pricing.bundleFeature5": "ການເຂົ້າເຖິງຊຸມຊົນ VIP",
    "pricing.bundleFeature6": "ການໂທປຶກສາກົນລະຍຸດປະຈຳເດືອນ",
    "pricing.ctaTitle": "ມີຄຳຖາມກ່ຽວກັບລາຄາບໍ?",
    "pricing.ctaDescription": "ຕິດຕໍ່ທີມງານຂອງພວກເຮົາສຳລັບວິທີແກ້ໄຂແບບກຳນົດເອງຫຼືການສອບຖາມໃດໆ.",
    
    // Contact Page
    "contact.title": "ຕິດຕໍ່ພວກເຮົາ",
    "contact.subtitle": "ພວກເຮົາຢູ່ທີ່ນີ້ເພື່ອຊ່ວຍໃຫ້ທ່ານປະສົບຜົນສຳເລັດ",
    "contact.tagline": "ຕິດຕໍ່ພວກເຮົາ",
    "contact.heroTitle": "ຕິດຕໍ່",
    "contact.heroHighlight": "ພວກເຮົາ",
    "contact.heroDescription": "ມີຄຳຖາມກ່ຽວກັບລະບົບ EA ຂອງພວກເຮົາບໍ? ທີມງານຂອງພວກເຮົາພ້ອມຊ່ວຍເຫຼືອ.",
    "contact.lineFastest": "ເວລາຕອບສະໜອງໄວທີ່ສຸດ",
    "contact.telegram247": "ຊ່ອງທາງສະໜັບສະໜູນ 24/7",
    "contact.emailDetailed": "ສຳລັບການສອບຖາມລະອຽດ",
    "contact.facebookCommunity": "ອັບເດດຊຸມຊົນ",
    "contact.sendMessage": "ສົ່ງຂໍ້ຄວາມຫາພວກເຮົາ",
    "contact.name": "ຊື່",
    "contact.namePlaceholder": "ຊື່ຂອງທ່ານ",
    "contact.email": "ອີເມວ",
    "contact.emailPlaceholder": "email@ຂອງທ່ານ.com",
    "contact.subject": "ຫົວຂໍ້",
    "contact.subjectPlaceholder": "ພວກເຮົາຊ່ວຍໄດ້ແນວໃດ?",
    "contact.message": "ຂໍ້ຄວາມ",
    "contact.messagePlaceholder": "ບອກພວກເຮົາເພີ່ມເຕີມກ່ຽວກັບການສອບຖາມຂອງທ່ານ...",
    "contact.send": "ສົ່ງຂໍ້ຄວາມ",
    "contact.supportInfo": "ຂໍ້ມູນການສະໜັບສະໜູນ",
    "contact.workingHours": "ເວລາເຮັດວຽກ",
    "contact.weekday": "ຈັນ - ສຸກ: 9:00 - 21:00 (GMT+7)",
    "contact.weekend": "ທ້າຍອາທິດ: 10:00 - 18:00 (GMT+7)",
    "contact.responseTime": "ເວລາຕອບສະໜອງ",
    "contact.lineTelegram": "Line / Telegram",
    "contact.technicalIssues": "ບັນຫາດ້ານເທັກນິກ",
    "contact.priority": "ບູລິມະສິດ",
    "contact.premiumSupport": "ການສະໜັບສະໜູນພຣີມຽມ",
    "contact.premiumDescription": "ຜູ້ສະໝັກ Bundle ໄດ້ຮັບການສະໜັບສະໜູນບູລິມະສິດດ້ວຍການຊ່ວຍເຫຼືອທີ່ອຸທິດຕົນ ແລະ ການໂທປຶກສາກົນລະຍຸດປະຈຳເດືອນ.",
    "contact.messageSent": "ສົ່ງຂໍ້ຄວາມແລ້ວ!",
    "contact.messageSuccess": "ພວກເຮົາຈະຕິດຕໍ່ກັບພາຍໃນ 24 ຊົ່ວໂມງ.",
    
    // FAQ Page
    "faq.title": "ຄຳຖາມທີ່ພົບເລື້ອຍ",
    "faq.subtitle": "ຊອກຫາຄຳຕອບສຳລັບຄຳຖາມທົ່ວໄປ",
    "faq.tagline": "ຄຳຖາມທີ່ພົບເລື້ອຍ",
    "faq.heroTitle": "ຄຳຖາມທີ່ຖາມ",
    "faq.heroHighlight": "ເລື້ອຍໆ",
    "faq.heroDescription": "ຊອກຫາຄຳຕອບສຳລັບຄຳຖາມທົ່ວໄປກ່ຽວກັບລະບົບການຊື້ຂາຍ EA ຂອງພວກເຮົາ.",
    "faq.generalQuestions": "ຄຳຖາມທົ່ວໄປ",
    "faq.capitalInvestment": "ທຶນ & ການລົງທຶນ",
    "faq.technicalRequirements": "ຄວາມຕ້ອງການດ້ານເທັກນິກ",
    "faq.subscriptionSupport": "ການສະໝັກ & ການສະໜັບສະໜູນ",
    "faq.stillHaveQuestions": "ຍັງມີຄຳຖາມອີກບໍ?",
    "faq.cantFind": "ຊອກຫາສິ່ງທີ່ທ່ານຕ້ອງການບໍ່ພົບ? ທີມງານສະໜັບສະໜູນຂອງພວກເຮົາພ້ອມຊ່ວຍເຫຼືອ.",
    "faq.contactSupport": "ຕິດຕໍ່ຝ່າຍສະໜັບສະໜູນ",
    
    // Performance Page
    "performance.title": "ຜົນງານສົດ",
    "performance.subtitle": "ຜົນການຊື້ຂາຍທີ່ຢັ້ງຢືນແບບເວລາຈິງ",
    "performance.tagline": "ຜົນງານສົດ",
    "performance.heroTitle": "ຜົນລັບທີ່",
    "performance.heroHighlight": "ຢັ້ງຢືນ",
    "performance.heroDescription": "ຂໍ້ມູນຜົນງານແບບເວລາຈິງຈາກບັນຊີການຊື້ຂາຍສົດຂອງພວກເຮົາ. ຜົນລັບທັງໝົດຖືກຕິດຕາມ ແລະ ຢັ້ງຢືນຜ່ານ Myfxbook.",
    "performance.totalReturn": "ຜົນຕອບແທນລວມ",
    "performance.live": "ສົດ",
    "performance.monthlyAvg": "ສະເລ່ຍເດືອນ",
    "performance.maxDD": "DD ສູງສຸດ",
    "performance.winRate": "ອັດຕາຊະນະ",
    "performance.profitFactor": "Profit Factor",
    "performance.equityCurve": "ເສັ້ນໂຄ້ງທຶນ (12 ເດືອນ)",
    "performance.startingBalance": "ຍອດເລີ່ມຕົ້ນ: $10,000",
    "performance.monthlyReturns": "ຜົນຕອບແທນລາຍເດືອນ (%)",
    "performance.detailedStats": "ສະຖິຕິລະອຽດ",
    "performance.totalTrades": "ການຊື້ຂາຍທັງໝົດ",
    "performance.tradingDays": "ວັນການຊື້ຂາຍ",
    "performance.sharpeRatio": "Sharpe Ratio",
    "performance.monthlyAverage": "ສະເລ່ຍເດືອນ",
    "performance.maxDrawdown": "Drawdown ສູງສຸດ",
    "performance.myfxbookTitle": "ການຢັ້ງຢືນ Myfxbook ສົດ",
    "performance.myfxbookDescription": "ເບິ່ງຜົນການຊື້ຂາຍສົດທີ່ຢັ້ງຢືນຢ່າງເຕັມທີ່ຂອງພວກເຮົາໃນ Myfxbook",
    "performance.viewMyfxbook": "ເບິ່ງໃນ Myfxbook",
    "performance.ctaTitle": "ເລີ່ມການຊື້ຂາຍດ້ວຍ",
    "performance.ctaHighlight": "ຜົນລັບທີ່ພິສູດແລ້ວ",
    "performance.ctaDescription": "ເຂົ້າຮ່ວມຊຸມຊົນນັກເທຣດອັດຕະໂນມັດທີ່ປະສົບຜົນສຳເລັດທີ່ເຕີບໂຕຂຶ້ນຂອງພວກເຮົາ.",
    
    // Copy Trade Page
    "copyTrade.tagline": "ບໍລິການ Copy Trade",
    "copyTrade.heroTitle": "ຄັດລອກນັກເທຣດມືອາຊີບ",
    "copyTrade.heroHighlight": "ອັດຕະໂນມັດ",
    "copyTrade.heroDescription": "ບໍ່ມີເວລາເທຣດບໍ? ໃຫ້ນັກເທຣດຜູ້ຊ່ຽວຊານຂອງພວກເຮົາເຮັດແທນທ່ານ. ຄັດລອກການຊື້ຂາຍຂອງພວກເຂົາອັດຕະໂນມັດ ແລະ ເຕີບໂຕບັນຊີຂອງທ່ານດ້ວຍຄວາມພະຍາຍາມໜ້ອຍທີ່ສຸດ.",
    "copyTrade.startCopyTrading": "ເລີ່ມ Copy Trading",
    "copyTrade.askQuestions": "ຖາມຄຳຖາມ",
    "copyTrade.activeCopiers": "ຜູ້ຄັດລອກທີ່ໃຊ້ງານ",
    "copyTrade.copiedVolume": "ປະລິມານທີ່ຄັດລອກ",
    "copyTrade.autoTrading": "ການຊື້ຂາຍອັດຕະໂນມັດ",
    "copyTrade.whyChooseTitle": "ເປັນຫຍັງຕ້ອງເລືອກ",
    "copyTrade.whyChooseHighlight": "Copy Trade",
    "copyTrade.whyChooseDescription": "ສຳຜັດຜົນປະໂຫຍດຂອງການຊື້ຂາຍມືອາຊີບໂດຍບໍ່ຕ້ອງຮຽນຮູ້.",
    "copyTrade.easyCopyTrading": "Copy Trading ງ່າຍໆ",
    "copyTrade.easyCopyTradingDesc": "ຄັດລອກການຊື້ຂາຍຈາກນັກເທຣດມືອາຊີບອັດຕະໂນມັດ. ບໍ່ຕ້ອງການປະສົບການການຊື້ຂາຍ.",
    "copyTrade.provenPerformance": "ຜົນງານທີ່ພິສູດແລ້ວ",
    "copyTrade.provenPerformanceDesc": "ຕິດຕາມນັກເທຣດທີ່ມີປະຫວັດການຊື້ຂາຍທີ່ຢັ້ງຢືນ ແລະ ຄວາມສາມາດທຳກຳໄລທີ່ສະໝ່ຳສະເໝີ.",
    "copyTrade.riskManagement": "ການຄຸ້ມຄອງຄວາມສ່ຽງ",
    "copyTrade.riskManagementDesc": "ຕັ້ງຄ່າຂີດຈຳກັດຄວາມສ່ຽງ ແລະ ພາຣາມິເຕີ stop-loss ຂອງທ່ານເອງສຳລັບການຄວບຄຸມຢ່າງເຕັມທີ່.",
    "copyTrade.realTimeExecution": "ການປະຕິບັດແບບເວລາຈິງ",
    "copyTrade.realTimeExecutionDesc": "ການຊື້ຂາຍຖືກຄັດລອກທັນທີໄປຫາບັນຊີຂອງທ່ານດ້ວຍຄວາມຊັກຊ້າໜ້ອຍທີ່ສຸດ.",
    "copyTrade.howItWorksTitle": "ວິທີການ",
    "copyTrade.howItWorksHighlight": "ເຮັດວຽກ",
    "copyTrade.howItWorksDescription": "ເລີ່ມຕົ້ນໃນສີ່ຂັ້ນຕອນງ່າຍໆ ແລະ ເລີ່ມຄັດລອກການຊື້ຂາຍມື້ນີ້.",
    "copyTrade.step1Title": "ເລືອກຜູ້ໃຫ້ສັນຍານ",
    "copyTrade.step1Desc": "ເລືອກນັກເທຣດທີ່ຢັ້ງຢືນແລ້ວຂອງພວກເຮົາ ແລະ ເລືອກຜູ້ທີ່ກົງກັບຄວາມອົດທົນຕໍ່ຄວາມສ່ຽງ ແລະ ຮູບແບບການຊື້ຂາຍຂອງທ່ານ.",
    "copyTrade.step2Title": "ເຊື່ອມຕໍ່ບັນຊີຂອງທ່ານ",
    "copyTrade.step2Desc": "ເຊື່ອມຕໍ່ບັນຊີການຊື້ຂາຍ MT4/MT5 ຂອງທ່ານຢ່າງປອດໄພ. ເງິນຂອງທ່ານຢູ່ກັບໂບຣກເກີຂອງທ່ານ.",
    "copyTrade.step3Title": "ຕັ້ງຄ່າພາຣາມິເຕີ",
    "copyTrade.step3Desc": "ກຳນົດຂະໜາດ lot, ຂີດຈຳກັດຄວາມສ່ຽງ, ແລະ ຄູ່ໃດທີ່ຈະຄັດລອກ. ການຄວບຄຸມຢ່າງເຕັມທີ່ເປັນຂອງທ່ານ.",
    "copyTrade.step4Title": "ເລີ່ມຄັດລອກ",
    "copyTrade.step4Desc": "ການຊື້ຂາຍຖືກຄັດລອກອັດຕະໂນມັດໄປຫາບັນຊີຂອງທ່ານແບບເວລາຈິງ. ນັ່ງກັບ ແລະ ເບິ່ງ.",
    "copyTrade.benefitsTitle": "ທຸກຢ່າງທີ່ທ່ານຕ້ອງການເພື່ອ",
    "copyTrade.benefitsHighlight": "ປະສົບຜົນສຳເລັດ",
    "copyTrade.benefitsDescription": "ບໍລິການ copy trading ຂອງພວກເຮົາຖືກອອກແບບມາເພື່ອເຮັດໃຫ້ການຊື້ຂາຍອັດຕະໂນມັດເຂົ້າເຖິງໄດ້ສຳລັບທຸກຄົນ, ບໍ່ວ່າລະດັບປະສົບການໃດ.",
    "copyTrade.benefit1": "ບໍ່ຕ້ອງການປະສົບການການຊື້ຂາຍ",
    "copyTrade.benefit2": "ການກຳນົດຂະໜາດຕຳແໜ່ງອັດຕະໂນມັດ",
    "copyTrade.benefit3": "ການຄັດລອກການຊື້ຂາຍແບບເວລາຈິງ",
    "copyTrade.benefit4": "ເລືອກຈາກຜູ້ໃຫ້ສັນຍານຫຼາຍຄົນ",
    "copyTrade.benefit5": "ຕັ້ງຄ່າຂີດຈຳກັດຄວາມສ່ຽງຂອງທ່ານເອງ",
    "copyTrade.benefit6": "ປະຫວັດຜົນງານທີ່ໂປ່ງໃສ",
    "copyTrade.benefit7": "ຕັ້ງຄ່າງ່າຍໃນນາທີ",
    "copyTrade.benefit8": "ເຮັດວຽກກັບໂບຣກເກີ MT4/MT5 ໃດກໍໄດ້",
    "copyTrade.proSignalProvider": "ຜູ້ໃຫ້ສັນຍານ Pro",
    "copyTrade.topPerforming": "ນັກເທຣດທີ່ດີທີ່ສຸດ",
    "copyTrade.monthlyReturn": "ຜົນຕອບແທນລາຍເດືອນ",
    "copyTrade.tradingSince": "ເທຣດຕັ້ງແຕ່",
    "copyTrade.copyThisTrader": "ຄັດລອກນັກເທຣດນີ້",
    "copyTrade.simplePricing": "ລາຄາ",
    "copyTrade.pricingHighlight": "ງ່າຍໆ",
    "copyTrade.pricingDescription": "ເລືອກແພັກເກດທີ່ເໝາະກັບຄວາມຕ້ອງການການຊື້ຂາຍຂອງທ່ານ. ບໍ່ມີຄ່າທຳນຽມທີ່ເຊື່ອງໄວ້.",
    "copyTrade.fullAccess": "ການເຂົ້າເຖິງບໍລິການ copy trading ເຕັມຮູບແບບ",
    "copyTrade.pricingFeature1": "ການຄັດລອກການຊື້ຂາຍບໍ່ຈຳກັດ",
    "copyTrade.pricingFeature2": "ຜູ້ໃຫ້ສັນຍານຫຼາຍຄົນ",
    "copyTrade.pricingFeature3": "ການປະຕິບັດແບບເວລາຈິງ",
    "copyTrade.pricingFeature4": "ເຄື່ອງມືການຄຸ້ມຄອງຄວາມສ່ຽງ",
    "copyTrade.pricingFeature5": "ການສະໜັບສະໜູນ 24/7",
    "copyTrade.pricingFeature6": "ການວິເຄາະຜົນງານ",
    "copyTrade.ctaTitle": "ພ້ອມທີ່ຈະເລີ່ມ",
    "copyTrade.ctaHighlight": "Copy Trading",
    "copyTrade.ctaDescription": "ເຂົ້າຮ່ວມກັບນັກເທຣດຫຼາຍຮ້ອຍຄົນທີ່ກຳລັງຄັດລອກສັນຍານຜູ້ຊ່ຽວຊານຂອງພວກເຮົາ ແລະ ເຕີບໂຕບັນຊີຂອງພວກເຂົາອັດຕະໂນມັດ.",
    "copyTrade.viewAllPlans": "ເບິ່ງແພັກເກດທັງໝົດ",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
